name: Agent Architect - Child
description: Created/assigned by architect only.
title: "[SWE] "
labels: ["aa:child", "aa:delegated-by-architect"]
body:
  - type: markdown
    attributes:
      value: |
        **Required header:**
        - Parent: #
        - Owner-Agent:
        - Gate:
        - Dependencies:
        
        **Assignment note (GitHub Custom Agent):**
        - After creation, run Copilot MCP assignment with: `owner`, `repo`, `issue_number`, `custom_instructions`, `custom_agent`, `model`
        - `custom_agent` must match `Owner-Agent` and `model` must match that agent profile
  - type: textarea
    id: brief
    attributes:
      label: Brief
      description: What to do + scope boundaries.
    validations:
      required: true
  - type: textarea
    id: ac
    attributes:
      label: Acceptance Criteria
      description: Testable criteria.
    validations:
      required: true
